//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_CommentTable
    {
        public System.Guid Id { get; set; }
        public string DestinationUserId { get; set; }
        public string SourceUserId { get; set; }
        public System.Guid PostId { get; set; }
        public string CommentMessage { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
