//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_EventRegistrationFromOrganizer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CH_EventRegistrationFromOrganizer()
        {
            this.CH_VoteTable = new HashSet<CH_VoteTable>();
            this.OTP_VerificationTable = new HashSet<OTP_VerificationTable>();
        }
    
        public System.Guid EventId { get; set; }
        public string OrganizerId { get; set; }
        public string NameofOrganizer { get; set; }
        public string EventName { get; set; }
        public Nullable<int> modeofevent { get; set; }
        public Nullable<int> TypeOfEvent { get; set; }
        public int SubTypeOfEvent { get; set; }
        public Nullable<int> ImageorVideoforEvent { get; set; }
        public Nullable<int> StreamOfParticipants { get; set; }
        public Nullable<int> AgeGroup { get; set; }
        public Nullable<int> MaxnumofTeam { get; set; }
        public Nullable<int> numofParticipantsinteam { get; set; }
        public Nullable<System.DateTime> StartofEventRegistration { get; set; }
        public Nullable<System.DateTime> EndOfEventRegistration { get; set; }
        public Nullable<System.DateTime> StartofVideoUpload { get; set; }
        public Nullable<System.DateTime> EndOfVideoUpload { get; set; }
        public Nullable<System.DateTime> StartOfValuationfromvoters { get; set; }
        public Nullable<System.DateTime> EndofValuationFromVoters { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public string FirstPrize { get; set; }
        public string SecondPrize { get; set; }
        public string ThirdPrize { get; set; }
        public byte[] EventImage { get; set; }
        public byte[] EventVideo { get; set; }
        public Nullable<int> EventStatus { get; set; }
        public Nullable<bool> Eventdisplayonhomepage { get; set; }
        public Nullable<int> Eventfee { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<System.DateTime> CurrentDateandTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CH_VoteTable> CH_VoteTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTP_VerificationTable> OTP_VerificationTable { get; set; }
    }
}
