//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_Judges
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Expertise { get; set; }
        public Nullable<int> Year_of_Experience { get; set; }
        public Nullable<bool> Invited { get; set; }
        public Nullable<int> Fee_per_Hour { get; set; }
        public Nullable<bool> Requested { get; set; }
        public Nullable<System.DateTime> RequestedDateTime { get; set; }
        public Nullable<System.DateTime> InvitedDateTime { get; set; }
        public Nullable<System.DateTime> AcceptedDateTime { get; set; }
        public Nullable<int> Totalnumberofhours { get; set; }
    }
}
