//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_LastLogin
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string SessionToken { get; set; }
        public Nullable<System.DateTime> CreatedDateandTime { get; set; }
        public Nullable<System.DateTime> ExpiryDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
