//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_MainPhotos
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> PhotosId { get; set; }
        public byte[] BannerPicData { get; set; }
        public byte[] ProfilePicData { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
