//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_OrganiztionAboutUs
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string NameOfOrganization { get; set; }
        public Nullable<System.DateTime> StartedInTheYear { get; set; }
        public string Address { get; set; }
        public Nullable<long> ContactNumber { get; set; }
        public string VisionofTheOrganization { get; set; }
        public string MissionOfTheOrganization { get; set; }
        public string Selfdesctiption { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> Fax { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
