//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_ParticipantRegistration
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
        public string OrganizerId { get; set; }
        public string ParticipantId { get; set; }
        public string Name { get; set; }
        public string CollegeorSchool { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> DateOfBirthh { get; set; }
        public Nullable<long> ContactNumber { get; set; }
        public string About_Self { get; set; }
        public Nullable<int> Modeofcompitetion { get; set; }
        public Nullable<int> RegistrationStatus { get; set; }
        public Nullable<int> ParticipantStatus { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public Nullable<System.Guid> ParticipantsPostId { get; set; }
        public Nullable<int> EventStatus { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateandTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
