//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_VoteTable
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public string userid { get; set; }
        public Nullable<bool> VoteStatus { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CH_EventRegistrationFromOrganizer CH_EventRegistrationFromOrganizer { get; set; }
        public virtual CH_VoteTable CH_VoteTable1 { get; set; }
        public virtual CH_VoteTable CH_VoteTable2 { get; set; }
    }
}
