//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConquerorHubEntities : DbContext
    {
        public ConquerorHubEntities()
            : base("name=ConquerorHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CH_BlockTable> CH_BlockTable { get; set; }
        public virtual DbSet<CH_CommentTable> CH_CommentTable { get; set; }
        public virtual DbSet<CH_CulturalVideos> CH_CulturalVideos { get; set; }
        public virtual DbSet<CH_EventRegistrationFromOrganizer> CH_EventRegistrationFromOrganizer { get; set; }
        public virtual DbSet<CH_HomePageData> CH_HomePageData { get; set; }
        public virtual DbSet<CH_Judges> CH_Judges { get; set; }
        public virtual DbSet<CH_LastLogin> CH_LastLogin { get; set; }
        public virtual DbSet<CH_Likes> CH_Likes { get; set; }
        public virtual DbSet<CH_MainPhotos> CH_MainPhotos { get; set; }
        public virtual DbSet<CH_OrganiztionAboutUs> CH_OrganiztionAboutUs { get; set; }
        public virtual DbSet<CH_ParticipantRegistration> CH_ParticipantRegistration { get; set; }
        public virtual DbSet<CH_ParticipantsAbout> CH_ParticipantsAbout { get; set; }
        public virtual DbSet<CH_ParticipantsGallery> CH_ParticipantsGallery { get; set; }
        public virtual DbSet<CH_ShareTable> CH_ShareTable { get; set; }
        public virtual DbSet<CH_SubComment> CH_SubComment { get; set; }
        public virtual DbSet<CH_SubscriptionTable> CH_SubscriptionTable { get; set; }
        public virtual DbSet<CH_VoteTable> CH_VoteTable { get; set; }
        public virtual DbSet<OTP_VerificationTable> OTP_VerificationTable { get; set; }
        public virtual DbSet<SessionToken> SessionTokens { get; set; }
        public virtual DbSet<Sponsor> Sponsors { get; set; }
        public virtual DbSet<CH_EventSubType> CH_EventSubType { get; set; }
    }
}
