//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquerorhub.SDK.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public byte[] Image { get; set; }
        public string Caption { get; set; }
        public Nullable<int> Like { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Private { get; set; }
        public Nullable<bool> Public { get; set; }
        public Nullable<System.DateTime> DateandTime { get; set; }
        public Nullable<System.Guid> ImageId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
